### PR TITLE
Warn on modified future frozen string literal

### PR DESCRIPTION
**Pull request by etiennebarrie**

### CODE REVIEW

**Comment by rubyFeedback** [comment]
With byroot suggesting it on the ruby tracker not too long ago, will it be proposed for an upcoming ruby developer meeting as well?

**Comment by casperisfine** [comment]
repro:
```ruby
o = "test"
def o.test
end
o.test
```

**Comment by casperisfine** [comment]
We'll need https://github.com/ruby/prism/pull/2577 to be fully green.

**Comment by casperisfine** [comment]
Alright, we're now at the stage where we're failing on `make test-spec`, which is being handled in https://github.com/ruby/spec/pull/1142

**Comment by casperisfine** [comment]
Moving to https://github.com/ruby/ruby/pull/10262

**Pull request closed without merging**
