### PR TITLE
Route around a bindgen bug where the ice->ic_cref field was incorrect

### PR DESCRIPTION
**Pull request by noahgibbs**
This was discovered when exploring https://github.com/Shopify/ruby/issues/233. But fixing this isn't enough to fix that bug. It does reduce generated code size and make Rust-YJIT output closer to CRuby-YJIT output, though. That's nice.

Specifically, the structure iseq_inline_constant_cache_entry in vm_core.h looks like this:

~~~
// imemo_constcache
struct iseq_inline_constant_cache_entry {
    VALUE flags;

    VALUE value;              // v0
    union ic_serial_entry ic_serial; // v1, v2
    const rb_cref_t *ic_cref; // v3
};
~~~

The field ic_cref is the only one after the somewhat-complex union field "ic_serial". Retrieving it from Rust as "(*ice).ic_cref" gives an incorrect value. However, adding a simple yjit.c wrapper for the field as "ice->cref" in C retrieves the correct value.

So: bindgen appears to be generating incorrect output for this structure and field.

### CODE REVIEW

**Comment by noahgibbs** [comment]
I should add a reproduction. Run the code below using "./miniruby --yjit test_struct.rb". Without this fix on Rust-YJIT you'll see the "opt_getinlinecache" generated code is quite long. With this fix, the code is much shorter. With head-of-main CRuby-YJIT you also get the short version.

~~~
# test_struct.rb
Point = Struct.new(:x, :y)

MyPoint = Point.new(3, 7);
puts "Try a thing, p: #{MyPoint.x.inspect}, #{MyPoint.y.inspect}"

def main
  STDERR.puts "P: #{MyPoint.x.inspect}, #{MyPoint.y.inspect}"
end

12.times { main }

puts RubyVM::YJIT::disasm(method(:main))
~~~

**Comment by maximecb** [comment]
Thanks for investigating this Noah :)

Can you add a previously failing regression test to `bootstraptest/test_yjit_rust_port.rb` and also add the same test to `bootstraptest/test_yjit.rb` (because we might discard test_yjit_rust_port.rb after the port, but we should keep this test).

Might also be good to open an issue on bindgen 🤔 Maybe just give them the failing struct layout and explain that the field after the union doesn't get its offset computed correctly.

**Comment by XrXr** [comment]
We are manually defining `union ic_serial_entry` as:

```rust
/// Opaque struct from vm_core.h
#[repr(C)]
pub struct ic_serial_entry {
    _data: [u8; 0],
    _marker:
    core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}
```

which of course doesn't have the correct size and so makes the offset for `ic_cref` wrong. Maybe we should take bindgen's output for the union instead? Though I guess we made the opaque type because bindgen's output is too large.

**Comment by noahgibbs** [comment]
Bindgen produces a fair bit for unions, yeah. That's a simpler union type than I had thought I saw, though, so more bindgen could easily be the most reasonable thing.

I should go through our opaque and bindgen types and make sure we don't have any other embedded opaque types in CRuby data structures. There's a decent chance this isn't the only place we have that bug.

**Comment by noahgibbs** [comment]
I'm not really sure how to write a regression test for this one. The direct effect of the bug is that opt_getinlinecache is significantly larger because of misreading ic_cref. But I don't think I can write a test at the test_yjit.rb level that directly checks offsets for the Rust data structures, and I don't think I'd want to. I could do a stats-enabled-only test that checks generated code size for a small method with opt_getinlinecache. But that would be fragile to other changes in code size.

I guess I could assert directly on the disassembly, but only do it when disassembly is active. If it can create a disassembly containing x86 assembly, it could check the output of disasm and see how many lines were in the opt_getinlinecache block. That's also fragile, but probably less so.

The more direct way to ensure the offset is correct is to somehow compare Rust's idea of the offset (or field value) with C's idea of it. That requires a getter written in C, either in the test code or yjit.c. It seems like a yjit.c getter would be easier, but it would also add slightly to runtime interpreter size.

So: would you prefer a disassembler-based test, a field-getter-based test, or both?

**Comment by maximecb** [comment]
I thought you had a crash for this but if there was not, don't worry about it.

**Review by maximecb — APPROVED** [review]

**Comment by noahgibbs** [comment]
So, Alan's right that we could just use bindgen for ic_serial_entry and that would fix this problem. Here's the extra bindgen output:

~~~
--- a/yjit/src/cruby_bindings.inc.rs
+++ b/yjit/src/cruby_bindings.inc.rs
@@ -1,5 +1,48 @@
 /* automatically generated by rust-bindgen 0.59.2 */

+#[repr(C)]
+pub struct __BindgenUnionField<T>(::std::marker::PhantomData<T>);
+impl<T> __BindgenUnionField<T> {
+    #[inline]
+    pub const fn new() -> Self {
+        __BindgenUnionField(::std::marker::PhantomData)
+    }
+    #[inline]
+    pub unsafe fn as_ref(&self) -> &T {
+        ::std::mem::transmute(self)
+    }
+    #[inline]
+    pub unsafe fn as_mut(&mut self) -> &mut T {
+        ::std::mem::transmute(self)
+    }
+}
+impl<T> ::std::default::Default for __BindgenUnionField<T> {
+    #[inline]
+    fn default() -> Self {
+        Self::new()
+    }
+}
+impl<T> ::std::clone::Clone for __BindgenUnionField<T> {
+    #[inline]
+    fn clone(&self) -> Self {
+        Self::new()
+    }
+}
+impl<T> ::std::marker::Copy for __BindgenUnionField<T> {}
+impl<T> ::std::fmt::Debug for __BindgenUnionField<T> {
+    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
+        fmt.write_str("__BindgenUnionField")
+    }
+}
+impl<T> ::std::hash::Hash for __BindgenUnionField<T> {
+    fn hash<H: ::std::hash::Hasher>(&self, _state: &mut H) {}
+}
+impl<T> ::std::cmp::PartialEq for __BindgenUnionField<T> {
+    fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
+        true
+impl<T> ::std::hash::Hash for __BindgenUnionField<T> {
+    fn hash<H: ::std::hash::Hasher>(&self, _state: &mut H) {}
+}
+impl<T> ::std::cmp::PartialEq for __BindgenUnionField<T> {
+    fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
+        true
+    }
+}
+impl<T> ::std::cmp::Eq for __BindgenUnionField<T> {}
 pub const INTEGER_REDEFINED_OP_FLAG: u32 = 1;
 pub const FLOAT_REDEFINED_OP_FLAG: u32 = 2;
 pub const STRING_REDEFINED_OP_FLAG: u32 = 4;
@@ -460,6 +503,12 @@ extern "C" {
 }
 pub type rb_num_t = ::std::os::raw::c_ulong;
 #[repr(C)]
+pub struct ic_serial_entry {
+    pub raw: __BindgenUnionField<rb_serial_t>,
+    pub data: __BindgenUnionField<[VALUE; 2usize]>,
+    pub bindgen_union_field: [u64; 2usize],
+}
+#[repr(C)]
 pub struct iseq_inline_constant_cache_entry {
     pub flags: VALUE,
     pub value: VALUE,
~~~

Any opinion on whether we should use that, @maximecb? I *think* it will de-dup, so we get the big chunk of output with our first union (this would be our first) but it looks like it shouldn't add as much for each additional union.

But that's a guess - I haven't tested to be sure.

**Comment by noahgibbs** [comment]
Eh, we've been dancing around unions in the data structures for awhile, and this has definitely bitten us now. I'll go ahead and merge the "use bindgen for the union" version of this, since having to know to use the getter for after-the-union fields in the struct is horrible, and will absolutely bite us later.

**Comment by maximecb** [comment]
I don't mind that the bindgen output is long since it's been automatically generated 👍

**Review by maximecb — APPROVED** [review]

**Pull request merged**
