### PR TITLE
Add gdbm dependencies to ruby builds with dbm.so

### PR DESCRIPTION
**Pull request by burke**
@shivnagarajan @csfrancis 

This does seem to make more sense.

### CODE REVIEW

**Comment by csfrancis** [comment]
What did you need this for out of curiousity?

**Comment by burke** [comment]
I'm probably going to use it for a refactor of `bootscale`: https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/load_path_cache/cache.rb

**Comment by burke** [comment]
So what's the process to actually get this shipped? It looks like we're using  2.3.3p222-shopify, so I should...

1. merge, and tag master as `ruby-shopify-2.3.3p222-shopify_1`
2. build on shipit, make sure package is there
3. bump in borg-baseimage

Is that right? It looks like baseimage has `declare -r rubby_version=2.3.3`. How would I tag this as a new build of the same revision?

**Comment by shivnagarajan** [comment]
That set of steps looks right. I think you can change the version in https://github.com/Shopify/borg-baseimage/blob/master/files/build.sh#L4 and/or add the version suffix (=2) into https://github.com/Shopify/borg-baseimage/blob/master/files/build.sh#L54

I've not tried this myself.. but normally it should work like that.

so maybe even

`rubby-version="2.3.3=2" may even work` ?

installing the package can specify the "version=" suffix according to https://packages.shopify.io/shopify/public/packages/ubuntu/precise/ruby-shopify-2.3.3_1~precise_amd64.deb

**Comment by burke** [comment]
I think I'm actually going to use LMDB for this thing instead, so I don't actively need this and won't bother with a release, but I'm going to merge anyway because it makes sense to me that future builds should have the full stdlib. Feel free to revert if you disagree.

**Pull request merged**
