### PR TITLE
Tie lifetime of uJIT blocks to iseqs

### PR DESCRIPTION
**Pull request by XrXr**
Blocks weren't being freed when iseqs are collected.

### CODE REVIEW

**Comment by XrXr** [comment]
I suppose when the entire method is going away, freeing all the blocks for it can be done more efficiently than invalidating individual blocks.

**Comment by maximecb** [comment]
This is a big change. Thanks for submitting this as a PR rather than pushing directly 🙏 . Maybe we could get by with a simpler solution? This PR adds a lot of complexity and introduces more coupling between blocks and the GC internals, which doesn't seem ideal.

What I was originally envisioning is that we would keep generating machine code until either of the code blocks get full. Then, we would essentially throw away all the generated code and the `block_t` objects as well. Similarly, we can also purge all the code and blocks when the process shuts down.

I imagine you want to keep track of block lifetimes because you want to update references in machine code, and you don't want to keep alive a bunch of old GC roots that aren't useful anymore. Is that correct?

I have two possible solutions to suggest:

1. If the Ruby GC supports that, make the references in the generated code weak references.
or
2. Keep track of which iseq a reference in the generated code is tied to, but don't add cc/cme/gc info to blocks themselves. Then when an iseq dies you can just nullify all of its references in machine code. You only need a list of addresses to nullify/remove for each iseq.

**Comment by XrXr** [comment]
We had a meeting about this and we decided that the following setup is okay for now:
  - remove `version_tbl` and make iseqs keep a list of `block_t`s
  - add array on `block_t` for list of objects that appear as immediates in generated code
  - keep `cc` and `cme` on blocks so when blocks can remove themselves from the method lookup dependency table during finalization.

**Comment by maximecb** [comment]
I liked your idea of using the `ccan` darray library for managing dynamic arrays as well. That should simplify code in a few places 👍

**Pull request merged**
