### PR TITLE
Better audit trail into Ruby builds + debug symbols by default

### PR DESCRIPTION
**Pull request by as3richa**
@csfrancis @shivnagarajan @camilo 

- Refactors `build.yml` to specify a history of builds rather than a single build - that way we don't have to cut and paste every time we need to bump Ruby.
- Makes a deploy via Shipit a no-op, and instead build packages by specifying name and version in a Shipit task.
- Gives `build.yml` the capacity to specify `configure` flags; builds debug symbols by default

### CODE REVIEW

**Comment by csfrancis** [comment]
Can't we just use git tags for this?

**Comment by as3richa** [comment]
I found the old git tag workflow really difficult to use. It took me way too long to figure out which revisions corresponded to which build, and that problem would only get worse if and when we start doing more custom builds (ie. Francis's future work). Also, I found the distinction between tags in `Shopify/ruby` and upstream tags to be counterintuitive.

Above and beyond that, we're encoding a lot more information here now for visibility (even before this PR) and it's not obvious to me where tags fit into that equation. What sort of workflow are you envisaging?

**Comment by csfrancis** [comment]
I just see that `build.yml` quickly growing out of control (similar to what happened with the yml file used by shopify-ruby).

A git tag can encode all of the information (aside from compilation flags, which I don't even think are really all that necessary) contained in one of the build.yml entry - we just need to define a convention, for example:
```
<package_name>_<package_version> = sha
ruby-shopify-2.3.1_2 = 0e64dc7b81d2a9c470a6c1bd2c3e327b5bb2ae96
```

For simplicity, I don't think the builder should be able to specify configuration flags. Any modification to configure flags should be done in the debian files and committed to git.

**Comment by as3richa** [comment]
Without the capacity to specify build flags, we lose the ability to do repeatable builds every time we change anything in the build process. But thinking back, maybe that shouldn't be a concern, because I already bumped bundler and nobody raised issues at that point, myself included. ¯\\_(ツ)_/¯

We would also lose the ability to add a memo to the packages, and I really think we'd lost some audit rail visibility 😭 But I do see your point re. `build.yml`. So if we have to lose those for the sake of an easier workflow, then let's do it.

**Comment by as3richa** [comment]
Bump @csfrancis 

I think this look okay now. Test stack here: https://shipit.shopify.io/shopify/ruby/staging/

**Comment by csfrancis** [comment]
LGTM.

**Pull request merged**
