### PR TITLE
Op::Nop for backend

### PR DESCRIPTION
**Pull request by kddnewton**
cc @noahgibbs

### CODE REVIEW

**Comment by noahgibbs** [comment]
Looks good to me. Do we want to allow Opnd::Imm as well as Opnd::UImm? I don't specifically need it, I just don't see a reason to exclude it.

**Comment by kddnewton** [comment]
I don't think we want signed numbers of bytes, because `NOP -5` doesn't make sense. I guess it could just mean do nothing, but that's not immediately obvious.

**Comment by maximecb** [comment]
It seems like this won't be needed after all @noahgibbs ?

We can probably close this PR for now and reopen it later if needed.

**Comment by noahgibbs** [comment]
Sounds like we won't need it, yeah.

**Comment by maximecb** [comment]
Closing for now since we'll rely on a different solution.

**Pull request closed without merging**
