### PR TITLE
Port send-only insns and write tests

### PR DESCRIPTION
**Pull request by k0kubun**
Ported instructions that require trivial effort now: send-only opt insns, insns with `todo!` on send, and opt_case_dispatch. Also added tests for them.

### CODE REVIEW

**Review by maximecb — APPROVED** [review]
Nice

**Comment by maximecb** [comment]
Excited to see how many more btests we can pass once this is merged 👌

**Review by noahgibbs — COMMENTED** [review]
This looks good. It took me a minute to be sure about the assert_equal chunks since they don't define a method, but I'm pretty sure the blocks they're in will get compiled with --yjit-call-threshold=1. It's sometimes tricky to make sure you get YJIT logic instead of interpreter logic :-)

**Comment by k0kubun** [comment]
> It took me a minute to be sure about the assert_equal chunks since they don't define a method, but I'm pretty sure the blocks they're in will get compiled with --yjit-call-threshold=1.

I didn't know about that, but it seems like it :) 

It generates a source file like <code>print(begin; "0" >= "1"; end)</code>. Because MJIT doesn't support it and YJIT shares the mjit_exec hook, I was believing a top-level ISeq would not be compiled, but excluding a top-level ISeq is done [here](https://github.com/ruby/ruby/blob/2f0d9e74c82c12d253ac808b636385ba27a4b115/mjit.c#L1631) instead of inside mjit_exec. So it seems like a top-level ISeq just comes to mjit_exec and YJIT compiles it too.

**Comment by noahgibbs** [comment]
Interesting. I know a lot of stuff in the top-level ISEQ does *not* seem to get run -- but that may be because we often get "random" side exits from things like cache misses. And so guaranteeing a particular line of code gets run in YJIT mode can be hard.

**Comment by maximecb** [comment]
YJIT has a polymorphic inline caches, so we'll only get a side-exit from a cache miss if it's highly polymorphic.

However, we do get side-exits to handle interrupts.

**Comment by k0kubun** [comment]
Assuming YJIT's polymorphic caching is enough for most cases, I'm interested in what interrupts we could get when we're not explicitly interrupting it like sending signals, because we'd like to minimize the occurrences. Maybe something that triggers `gc_finalize_deferred_register` is GC-ed, e.g. T_FILE?

**Comment by maximecb** [comment]
Not sure. It definitely seems like the GC could cause interrupts but I don't know the specifics of how CRuby interrupts work.

**Pull request merged**
