### PR TITLE
YJIT: get rid of dependency on rb_call_cache

### PR DESCRIPTION
**Pull request by XrXr**
Figure I would PR this first before using it for making opt_send_without_block polymorphic.

### CODE REVIEW

**Comment by XrXr** [comment]
Well, it looks like I'm running into problems with the bespoke weak reference setup due to trying to lift from the interpreter's call cache. Since it's a problem specific to trying to do that, I think it'd be best to lump these changes with making `opt_send_without_block` polymorphic.

**Comment by maximecb** [comment]
Can you explain in a bit more detail just so I can understand? Something is getting GC'd that shouldn't? Which are the weak references?

**Comment by XrXr** [comment]
https://github.com/Shopify/ruby/blob/fad3412d475b57055f426cf4e86eafeab516672b/vm_callinfo.h#L274-L280
`cd->cc->klass` is a weak reference, but we want a strong reference from the dependency table. (for now. It's leaky, and just for getting something going)
The assert failure in 2c0f61b is from trying to put an already collected class into the dependency table.

This is not a problem if codegen is deferred and happens just in time, because the class would come from a live object on the temp stack.

I guess for now I could make it bail if cc->klass is garbage, but it doesn't seem worth it since we are going to defer compilation soon anyways.

**Comment by XrXr** [comment]
Lumped with #83

**Pull request closed without merging**
